### PR TITLE
Validate Country Code before submitting

### PR DESCRIPTION
**Pull request by thatfreakcoder**
Regarding Issue #1 
I've added a simple `if` statement that validates whether the number has `+91` Country Code in the beginning or not through a simple RegEx `match()` method. If present, continues normally, else adds `+91` and continues normally.

### CODE REVIEW

**Comment by ayush5588** [comment]
Nice observation. But we also have to consider the fact that the message can be sent to a number outside of India. In that case I think adding +91 would not work. 
So to deal with that I think maybe if possible then there can be a field where the user can enter the country (where the message has to be sent) and then accordingly the Country Code can be added to the number.

**Comment by thatfreakcoder** [comment]
@ayush5588 yes, I too had this in my mind. but for such a simple app like this one, I don't think we should focus on validating it for every country but rather check our targeted audience and make it more seamless for them, and not put them through the process of selecting a country (and hence a country code)

**Comment by ayush5588** [comment]
@thatfreakcoder Yeah that seems right.

**Comment by iamyajat** [comment]
Hey @thatfreakcoder, I agree with @ayush5588 here. If a non Indian person is trying to contact someone, they might end up messaging the wrong person, if they forget to put the country code.
It would be great if you could do a country check and add their respective country code instead of just `+91`.
Peace

**Comment by thatfreakcoder** [comment]
yeah @iamyajat, i was working on a side project that implemented this, so will include that in a future update, for the time being, can you merge the current branch for `+91` indian code?

**Pull request closed without merging**
